include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    import_of_legacy_library_into_null_safe: false
    unused_import: error
    unused_field: error
    unused_local_variable: error
    unused_element: error
    unnecessary_import: error
    prefer_relative_imports: error
    require_trailing_commas: error

  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "lib/l10n/messages_*.dart"
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.gen.dart"

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    one_member_abstracts: false
    avoid_classes_with_only_static_members: false
    require_trailing_commas: true
    prefer_relative_imports: true
