name: flutter_channel_practice
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.10.2'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod:
  freezed_annotation:

dev_dependencies:
  build_runner:
  freezed:
  flutter_lints:

flutter:
  uses-material-design: true
