name: page_transaction
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.4'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod:
  freezed_annotation:

dev_dependencies:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
